### ISSUE TITLE
no more traces after enabling of profile

### ISSUE THREAD

**Issue by strwase** [gotdibbs/Imposter.Fiddler#13]
I have no idea if you are still using this plugin. 
I've been using it extensively for the last couple of years for my webresources development.

But I got a new laptop, reinstalled fiddler and imposter, but now as soon as I enable a profile, fiddler just stops tracing completely.

any help would be greatly appreciated

**Comment by gotdibbs** [comment]
I am not actively using it myself, but am happy to help troubleshoot!

To start, have you checked that HTTPS decryption is enabled? That's usually where problems start. You have to accept all the popups to actually install the decryption certificate: https://docs.telerik.com/fiddler/configure-fiddler/tasks/decrypthttps

**Comment by strwase** [comment]
Yeah, fiddler by itself runs fine. It just stops working when I enable an imposter profile. 

Are you not using it anymore because no more need for it, or did you find an alternative?

**Comment by gotdibbs** [comment]
Could you confirm for me:

1. Are you using Fiddler Classic, and the latest version from their website?
2. Are you using the latest version of Imposter for Fiddler that is posted under the Release section?

Assuming the above are true, I would try:

1. Go to the Imposter menu at the top left of Fiddler Classic
2. Uncheck "auto filter" and see if more traffic comes through

Assuming more traffic comes through after unchecking auto filter, then the issue is likely the structure of your filter. The requests being made aren't matching the filter. You can pull your old profiles from your old machine if that helps? Otherwise you'll have to debug that filter.

As an aside, I am not using it because I don't work on Dynamics projects anymore. I've changed industries. Would still love to support this if it makes sense, but can only devote so much outside of work time on it. I can say the debugging workflow for this tool was very straightforward though if you're familiar with C# at all.

**Comment by strwase** [comment]
I got it working, thanks.

If you don't work on Dynamics anymore, it makes sense you don't have need for this tool as much anymore.
For me, it's essential. So much easier in use then using the standard autoresponder functionality.

I'll dive into the code, if the need arises I'll see if I can do some of the patching.

grtz

**Comment by gotdibbs** [comment]
Glad to hear you got it working! Def let me know if there's something I can update with respect to documentation or a tweak to the UX or anything!

Happy to help with this where I can, whenever I can. I still have my own personal D365 instance to troubleshoot against if absolutely needed.
